#!/bin/sh

## hyphop ##

GIT=miZy-busybox
NAME=busybox
VER=1.30.1
PKG="$NAME-$VER.tar.bz2"
PKGD="$NAME-$VER"
ZDIR=/tmp/zero_builder
WDIR=/tmp/mizy-busybox
BDIR="$WDIR/$NAME"
SRV=https://www.busybox.net/downloads/
SRC="$SRV$PKG"
CDIR="$ZDIR/$GIT"
LOG=log
