#!/bin/sh

## hyphop ##

GIT=miZy-busybox
NAME=busybox
VER=1.30.1
PKG="$NAME-$VER.tar.bz2"
PKGD="$NAME-$VER"
ZDIR=../
WDIR=../miZy-busybox-wdir
BDIR="$WDIR/$NAME"
SRV=https://www.busybox.net/downloads/
SRC="$SRV$PKG"
CDIR="$PWD"
LOG=log
