#!/bin/sh

## hyphop ##

NAME=busybox
VER=1.30.1
PKG="$NAME-$VER.tar.bz2"
PKGD="$NAME-$VER"
WDIR=/tmp/mizy-busybox
ZDIR=/tmp/zero_builder
BDIR="$WDIR/$NAME"
SRV=https://www.busybox.net/downloads/
SRC="$SRV$PKG"
CDIR="$(realpath $(dirname $0))"

