#!/bin/sh

## hyphop ##

. "$(dirname $0)/,config"

INITRAMFS_DIR="$WDIR/initramfs"

echo "[i] display info about packed initramfs / rootfs">&2

mkdir -p "$INITRAMFS_DIR"

for S in $INITRAMFS_DIR.*.squashfs; do

    echo "# $S
$(ls -l1 $S)
">&2
#$(file $S)

done
